from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Application namespace
app_name = 'guestbook'

# Create a router for automatic URL routing of ViewSets
router = DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'entries', views.EntryViewSet)

# Define the urlpatterns for the guestbook app
urlpatterns = [
    # Include the URLs generated by the router for 'users' and 'entries' ViewSets
    path('', include(router.urls)),

    # Endpoint for creating a new entry
    path('create-entry/', views.CreateEntryView.as_view(), name='create-entry'),

    # Endpoint for retrieving users' data
    path('get-users-data/', views.GetUsersDataView.as_view(), name='get-users-data'),
]

